application_port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email:
  server: "test"
  port: 587
  username: "test"
  password: "password"
  sender: "test@test.com"
redis:
  host: "localhost"
  port: "6379"
  conn: "tcp"