name: Static-Check

on:
  push:
    branches:
      - main

  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

  workflow_dispatch:

jobs:
  staticcheck:
    name: Run Staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          version: "2023.1.6"
        
        
